-- The catalogue releases the app downloads, and the devices that download them.
--
-- A release is stored exactly as it was signed. The manifest is kept as raw bytes rather than a
-- parsed structure because the signature covers those bytes: re-serialising the JSON, even
-- identically in meaning, would change them and every device would reject the result.

create table gallery_release (
    version         integer      primary key,
    model_id        text         not null,
    embedding_dim   integer      not null,
    section_count   integer      not null,

    manifest        bytea        not null,   -- gallery.json, byte for byte as signed
    manifest_sha256 text         not null,
    signature       bytea        not null,   -- ECDSA P-256 over the manifest bytes, DER
    vectors         bytea        not null,   -- gallery.f32, count x dim float32 little-endian
    vectors_sha256  text         not null,   -- also stated inside the manifest, so signed too

    created_at      timestamptz  not null,   -- when the export ran
    published_at    timestamptz  not null default now(),
    notes           text
);

comment on table gallery_release is
    'Signed catalogue releases. The server holds no private key and cannot produce these.';

create table client_device (
    device_id       text         primary key,
    label           text,                    -- set by an administrator: "warehouse 2, phone 3"
    first_seen_at   timestamptz  not null default now(),
    last_seen_at    timestamptz  not null default now(),
    last_sync_at    timestamptz,             -- last time it actually took a new release
    gallery_version integer      references gallery_release (version),
    app_version     text,
    android_release text,
    device_model    text,
    sync_count      integer      not null default 0,
    last_ip         text
);

comment on column client_device.device_id is
    'Generated by the app on first run and kept in its private storage. Identifies an install, not a person.';

create table sync_event (
    id           bigserial    primary key,
    device_id    text         not null references client_device (device_id),
    at           timestamptz  not null default now(),
    action       text         not null,      -- check_in | download | publish
    from_version integer,
    to_version   integer,
    ip           text,
    user_agent   text
);

create index sync_event_device_at_idx on sync_event (device_id, at desc);
create index sync_event_at_idx on sync_event (at desc);

comment on table sync_event is
    'Audit trail: which device asked for what and when. The record of who is running the app.';
